# Generated by Django 3.2.15 on 2022-09-24 16:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'description'])),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'moderate'), (3, 'challenging')], default=1)),
                ('equipment', models.TextField(max_length=300)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stars', models.ManyToManyField(blank=True, related_name='bake_stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('bake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bakes.bake')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='BestFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_for', models.IntegerField(choices=[(1, 'Brunch'), (2, 'Kids'), (3, 'Parties'), (4, 'Sharing'), (5, 'Birthdays'), (6, 'Christmas'), (7, 'Weekend Baking'), (8, 'Simple Baking')], default=1)),
                ('bake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakes.bake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['best_for'],
            },
        ),
    ]
