# Generated by Django 3.2.15 on 2023-01-26 05:27

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bake',
            name='equipment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bake',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
