# Generated by Django 3.2.15 on 2023-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakes', '0002_auto_20230126_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bake',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
